#!/bin/bash

export PCDS_CONDA_VER=6.0.1
# shellcheck disable=SC1091
source /cds/group/pcds/pyps/conda/pcds_conda ""

# Find full path of release directory.  This script is in
# $RELDIR/scripts/launch_gui.sh, so we need to chop off the
# last two path components.
RELDIR="$(readlink -f "$0")"
RELDIR="$(dirname "$RELDIR")"
RELDIR="$(dirname "$RELDIR")"
PYTHONPATH="$RELDIR"

export RELDIR
export PYTHONPATH
python "$RELDIR"/scripts/switch_gui.py "$@"
